### ISSUE TITLE
Latest 335 built farming station doesn't directly output to ender chest anymore

### ISSUE THREAD

**Issue by SubsterNL** [CrazyPants/EnderIO#1825] opened 2015-02-02 14:21 UTC
Latest 335 built farming station doesn't directly output to ender chest anymore.

It worked fine before.. The small internal 4 slot buffer runs ful and it shows output full over the station and it just stops doing anything.. The IO is set correctly to push (wasn't changed).

**Comment by tterrag1098** [comment] 2015-02-02 14:29
Screenshot? Which ender chest?

**Comment by Hazado** [comment] 2015-02-02 15:27
Im also having this happen with the sag mill in push/pull mode but with a regular chest. Nothing changed, but updating to the latest version.

**Comment by thehobojoe** [comment] 2015-02-02 18:36
Push is broken for all machines in build #333

**Comment by tterrag1098** [comment] 2015-02-02 19:11
Dupe of #1824

**Closed** 2015-02-02 19:11 UTC
