### ISSUE TITLE
EnderIO Crash when removing Universal Cable from Capacitor Bank

### ISSUE THREAD

**Issue by CandiceJoy** [CrazyPants/EnderIO#1679] opened 2015-01-15 08:30 UTC
Reproduction: <DemoXin> Fairly certain that I just crashed the server by removing a universal cable from a capacitor bank.
Crash report: http://pastebin.com/h7uusCCy

**Comment by 6210classick** [comment] 2015-01-15 17:46
why not use EIO energy conduit since capacitor banks are also from EIO

it's probably because of old RF API  , try updating to the latest Mekanism version and FORGE

**Comment by MatthiasMann** [comment] 2015-01-15 22:56
This should have been fixed in build 320 - can you try with that or a later build?

**Comment by tterrag1098** [comment] 2015-01-20 01:22
Duplicate of #1433

**Closed by tterrag1098** 2015-01-20 01:22 UTC
Labels: bug, Code Complete, Duplicate
