### ISSUE TITLE
Ender io Wither Skeleton 

### ISSUE THREAD

**Issue by MrSaySpuds** [CrazyPants/EnderIO#1958] opened 2015-02-18 01:50 UTC
Hi there i am having a problem with Ender IO Wither Skeleton 
It's None stop spawning in the nether and not chunck loaded, Reporting it here, (Update EnderIO-1.7.10-2.2.8.349) 
![2015-02-18_01 39 04](https://cloud.githubusercontent.com/assets/11053674/6241140/48bbf03a-b710-11e4-86e0-e1b305de1fd2.png)

**Comment by 6210classick** [comment] 2015-02-18 07:33
i don't think it's intended as a problem because in the latest version Skeletons & Wither Skeletons are now treated as separate entities so you will probably find them a lot more than it used to be ,, you can disable this in the config if you want

but try resetting the nether and see if the problem still occurs

**Comment by Robijnvogel** [comment] 2015-02-18 10:37
#1899 is about this same issue

**Comment by HenryLoenwind** [comment] 2015-02-18 10:44
@6210classick Them being treated as different entities should not increase any kind of spawn rate. Our code only converts Skeletons that spawn as "wither" to Wither Skeletons, it does not spawn them by itself..

**Comment by tterrag1098** [comment] 2015-02-22 23:54
Duplicate of #1899

**Closed by tterrag1098** 2015-02-22 23:54 UTC
