### ISSUE TITLE
Insulated conduit switch?

### ISSUE THREAD

**Issue by hisorange** [CrazyPants/EnderIO#2088] opened 2015-03-14 19:07 UTC
Aye, I love the current conduit switches, they look way better than having a cobblestone lever in any building, but I tend to have a simple problem with them, those switches only good if you wana turn on the red channel for something, since we got those cool channels wouldn't it be awesome to use those switches on them? 

I know the workaround is easy just build a separate system turn that on, provide strong signal, and read it back with the channel you want, but even tho we got a map bigger than the earth we tend to build our conceptions as small as possible, thats why I always use conduits :D

I hope it makes sense :D

**Comment by 6210classick** [comment] 2015-03-14 23:19
i'm also wondering why this isn't a thing but mainly because nobody uses the conduit switcher that much even if a new one implemented that uses the color system people still gonna use the ugly vanilla lever i blame the lever for this one

**Comment by tterrag1098** [comment] 2015-03-16 03:24
Duplicate of #1741

**Closed by tterrag1098** 2015-03-16 03:24 UTC
