### ISSUE TITLE
here u go another crash by enderio cap

### ISSUE THREAD

**Issue by Flukethoughts** [CrazyPants/EnderIO#1606] opened 2015-01-07 02:09 UTC
---- Minecraft Crash Report ----
// There are four lights!

Time: 1/6/15 3:08 PM
Description: Exception in server tick loop

java.lang.NullPointerException: Exception in server tick loop
	at TEnergyHandler$$11$class.receiveEnergy(Unknown Source)
	at TileMultipart_cmp$$39.receiveEnergy(Unknown Source)
	at crazypants.enderio.power.EnergyReceiverPI.recieveEnergy(EnergyReceiverPI.java:66)
	at crazypants.enderio.machine.capbank.network.CapBankNetwork.sendPowerTo(CapBankNetwork.java:291)
	at crazypants.enderio.machine.capbank.network.CapBankNetwork.transmitEnergy(CapBankNetwork.java:264)
	at crazypants.enderio.machine.capbank.network.CapBankNetwork.doNetworkTick(CapBankNetwork.java:221)
	at crazypants.enderio.machine.capbank.network.CapBankNetwork.access$100(CapBankNetwork.java:32)
	at crazypants.enderio.machine.capbank.network.CapBankNetwork$TickReciever.tickEnd(CapBankNetwork.java:542)
	at crazypants.enderio.conduit.ConduitNetworkTickHandler.tickEnd(ConduitNetworkTickHandler.java:47)
	at crazypants.enderio.conduit.ConduitNetworkTickHandler.onServerTick(ConduitNetworkTickHandler.java:35)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_171_ConduitNetworkTickHandler_onServerTick_ServerTickEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
	at cpw.mods.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:247)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:590)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

**Comment by tterrag1098** [comment] 2015-01-07 07:09
Duplicate of #1433

**Closed by tterrag1098** 2015-01-07 07:09 UTC
