### ISSUE TITLE
Crash on placing ME Conduit (rv2)

### ISSUE THREAD

**Issue by TheJulianJES** [CrazyPants/EnderIO#1843] opened 2015-02-04 13:57 UTC
When I place an ME Conduit in the same block space as an existing cable, the Client crashes: 
http://pastebin.com/50fv2wFM So I have to first place the ME Conduit (Dense) and then place other conduits (ender energy) Hope I'm doing all right, also sorry for my bad English, I'm German!
Only client crash, latest AE2 Beta, latest EnderIO Jenkins. In the crashlog you can see an older version of EnderIO but it's also in the newest version :)

**Comment by tterrag1098** [comment] 2015-02-04 17:06
This doesn't seem to happen for most people. Could we have a modlist?

**Comment by TheJulianJES** [comment] 2015-02-04 17:22
It was working in a earlier version of the private "modpack", but now it isn't: http://imgur.com/a/sRNiJ
I will try it with less mods.

**Comment by Akai1** [comment] 2015-02-06 02:06
Can confirm the crash: http://pastebin.com/JUxKB3Cf

**Comment by riking** [comment] 2015-02-06 07:08
In order for the bug to trigger, `net.minecraftforge.common.DimensionManager#getCurrentSaveRootDirectory(V)Ljava/lang/File;` returns null.

**Comment by MatthiasMann** [comment] 2015-02-06 07:13
When this issue occurs - does it also affect the Dimensional Transceiver's channel list?

**Comment by MatthiasMann** [comment] 2015-02-06 07:16
@Akai1 @TheJulianJES We need a description on how to reproduce this.

**Comment by TheJulianJES** [comment] 2015-02-06 12:52
@MatthiasMann For me place an ME Conduit (Dense) into an exisiting conduit.

**Comment by Akai1** [comment] 2015-02-06 13:32
@MatthiasMann Same for me ... tried to place an ME Conduit into an Ender Energy Conduit.

**Comment by MatthiasMann** [comment] 2015-02-06 18:22
That's not what I need - I have placed tons of normal and dense ME conduits in the world and on existing conduits. All code paths for placing any kind of ME conduit will query the AE2 player data base. And that tries to get the save folder from Forge the first time it is called - which in your cases was unable to find the save game location.

Even the crash report itself could not tell you which file format version your world save uses - so something is wrong in your setup.

**Comment by TheJulianJES** [comment] 2015-02-06 18:36
It was working for me in an earlier version in AE2 OR EnderIO. Maybe the API is outdated?

**Comment by TheJulianJES** [comment] 2015-02-06 18:37
Maybe "we" could ask @thatsIch or someone from the AE2 ;)

**Comment by riking** [comment] 2015-02-06 19:26
@Akai1 @TheJulianJES Are you placing the cables in the overworld, or in another dimension?

Has the overworld ever been loaded since the server started?

**Comment by Akai1** [comment] 2015-02-06 19:43
@riking Yeah placing the cables in the overworld. Map should be around 3 month old.

**Comment by TheJulianJES** [comment] 2015-02-06 19:54
@Akai1 @riking Overworld, all of the conduits are loaded with the newest version of Chicken Chunks Chunk Loaders

**Comment by ganzhorn** [comment] 2015-02-07 22:49
I have been seeing this issue as well.
Here's my client's crash log:
http://paste.atlauncher.com/view/2c0e505c
the stack trace is basically identical to what @Akai1 got.

It's very consistent for me, I get a client crash every single time I try to add an ME conduit to an existing conduit. Placing ME conduits by themselves works fine, and adding energy conduits to an existing ME conduit also works fine. (I'm doing all this in the overworld as well.)

I had used ME conduits before in a previous version of the RR modpack (3.2.2.1) without any problems. That was using Applied Energistics 2 rv2-Beta-5 and EnderIO 2.2.6.317. The version of the RR modpack I'm using now includes Applied Energistics 2 rv2-Beta-8 and EnderIO 2.2.7.331.

 @MatthiasMann (a) I don't have any dimensional transceivers placed, and (b) what can I get you besides the crash log that will help to reproduce this? You said:
> All code paths for placing any kind of ME conduit will query the AE2 player data base. And that tries to get the save folder from Forge the first time it is called - which in your cases was unable to find the save game location.
Where is the save folder you're referring to supposed to be? Let me know and I can check if it's actually there.

**Comment by riking** [comment] 2015-02-08 00:22
The save folder is something like `.minecraft/saves/World` or the folder with `ForgeServer.jar`.

Pretty sure it's there ;)

**Comment by ganzhorn** [comment] 2015-02-08 04:26
Yeah, my world folder is definitely present and accounted for; I thought @MatthiasMann was maybe asking about something inside it. I have an AE2 folder inside there, but I'm not sure if its contents are correct as I don't have anything to compare it to.

**Comment by Deckee** [comment] 2015-02-08 07:29
I've been able to to reproduce this crash more than once, i am using ender io EnderIO-1.7.10-2.2.8.344.jar and appliedenergistics2-rv2-beta-7.jar. from my modding experience this crash is caused when enderio try's to render the dense ae2 cable conduit in the existing conduit. The fix would be for @CrazyPants to rewrite the render code for the ME dense conduit.

**Comment by tterrag1098** [comment] 2015-02-08 07:35
@Deckee The above crash reports have nothing to do with rendering.

**Comment by Deckee** [comment] 2015-02-08 07:39
I am doing some investigating in to this crash, my crash report is pretty close to his.

**Comment by Deckee** [comment] 2015-02-08 08:02
found the problem, he has mekanism, enderio, ae2, galacticraft and morph. the probem is that  ae2, galacticraft and morph edit the player classes in the game. 
	at appeng.core.features.registries.PlayerRegistry.getID(PlayerRegistry.java:40) that is telling me that ae2 is trying to put a modified tag on to the cable (for the security mechanic) and one of the other mods does not like that at all.

**Comment by MatthiasMann** [comment] 2015-02-08 10:52
Not sure if this will solve the issue as I could not reproduce it locally.

**Comment by TheJulianJES** [comment] 2015-02-08 11:50
@MatthiasMann I will compile and try it ;)

**Comment by TheJulianJES** [comment] 2015-02-08 14:15
@MatthiasMann The PR didn't fixed it.

**Comment by MatthiasMann** [comment] 2015-02-08 14:24
Is the stack trace the same?

**Comment by TheJulianJES** [comment] 2015-02-08 14:29
Exactly the same.

**Comment by tjsd** [comment] 2015-02-09 16:25
@MatthiasMann I can confirm I no longer crash with your fix applied.

**Comment by Gunsmithy** [comment] 2015-02-11 04:33
I can't say if your additions fix it or not @MatthiasMann but I had the same issue as these people and it is on a server world as your fixes seem to imply the issue only affects. I'm using a whole bunch of mods but namely the ones mentioned before, EnderIO-1.7.10-2.2.8.344.jar and appliedenergistics2-rv2-beta-8.jar.

**Comment by TheJulianJES** [comment] 2015-02-12 16:14
#1910 maybe?

**Comment by Gunsmithy** [comment] 2015-02-12 16:17
@TheJulianJES Could be related, but I have no facades in my world at least.

**Comment by MatthiasMann** [comment] 2015-02-12 18:45
@TheJulianJES @Gunsmithy the referenced issue is using AE2 rv1 which is no longer supported by EnderIO - and as such not related at all with this issue

**Comment by BrendanTA** [comment] 2015-02-13 10:17
@MatthiasMann Even so, I'm using AE2 rv2 which has the crashing still when placed in the bundled cable.

**Comment by TheJulianJES** [comment] 2015-02-13 12:59
It has nothing to do with AE2, it's EnderIO, since I always used rv2 beta 8.

**Comment by MatthiasMann** [comment] 2015-02-13 17:29
@BrendanTA the crash on placing an ME conduit on an existing conduit bundle is fixed by the patches referenced in this bug.
Not everything is related - either read the crash logs very carefully or leave it to others.

**Comment by MatthiasMann** [comment] 2015-02-13 21:35
This issue should now be fixed with EnderIO 2.2.8 build 349 which is available on Curse.

**Comment by BrendanTA** [comment] 2015-02-13 21:54
@MatthiasMann Sorry for the mis-conception.

**Closed** 2015-02-14 20:25 UTC
Labels: bug, Cannot reproduce
