### ISSUE TITLE
Skelleton Spawn Bug in Nether

### ISSUE THREAD

**Issue by DnielMC** [CrazyPants/EnderIO#1827] opened 2015-02-02 19:11 UTC
As the title says there is a bug with Skeletons in the Nether. They spawn in an enormous mass in the Nether Fortress.
It all happened after I copied parts of my overworld map into an older version of it. (Had no backup)
After that I noticed a an console spam on my server.
Since the server is running I don'T get a crash report, but it says:
"java.lang.IllegalStateException: Entity Is a already tracked! at net.minecraft.entity.EntityTracker.func_72785_a<EntityTracker.java:196>*~[mn.class:?]"

Also some pictures:
http://imgur.com/a/QhnhS

**Comment by tterrag1098** [comment] 2015-02-02 19:12
Dupe of #1761

**Closed by tterrag1098** 2015-02-02 19:13 UTC
