### ISSUE TITLE
Server crash when disconnecting Mekanism cable from Capacitor Bank

### ISSUE THREAD

**Issue by aMUSiC** [CrazyPants/EnderIO#1583] opened 2015-01-05 02:24 UTC
Server: Cauldron-MCPC-Plus-1.7.10-1.1236.05.212
Mod: EnderIO-1.7.10-2.2.6.317

When a player attempts to break a cable that is directly connected to a Capacitor Bank, the server crashes. Any other cable (not directly attached) is fine. So is breaking the bank block that is attached to the cable. The cable tested was Mekanism's Ultimate Universal Cable.

Stacktrace follows.

[FML/]: Exception caught during firing event cpw.mods.fml.common.gameevent.TickEvent$ServerTickEvent@710f3e3c:
java.lang.NullPointerException
        at TEnergyReceiver$$19$class.receiveEnergy(Unknown Source) ~[?:?]
        at TileMultipart_cmp$$22.receiveEnergy(Unknown Source) ~[?:?]
        at crazypants.enderio.power.EnergyReceiverPI.recieveEnergy(EnergyReceiverPI.java:66) ~[EnergyReceiverPI.class:?]
        at crazypants.enderio.machine.capbank.network.CapBankNetwork.sendPowerTo(CapBankNetwork.java:291) ~[CapBankNetwork.class:?]
        at crazypants.enderio.machine.capbank.network.CapBankNetwork.transmitEnergy(CapBankNetwork.java:264) ~[CapBankNetwork.class:?]
        at crazypants.enderio.machine.capbank.network.CapBankNetwork.doNetworkTick(CapBankNetwork.java:221) ~[CapBankNetwork.class:?]
        at crazypants.enderio.machine.capbank.network.CapBankNetwork.access$100(CapBankNetwork.java:32) ~[CapBankNetwork.class:?]
        at crazypants.enderio.machine.capbank.network.CapBankNetwork$TickReciever.tickEnd(CapBankNetwork.java:542) ~[CapBankNetwork$TickReciever.class:?]
        at crazypants.enderio.conduit.ConduitNetworkTickHandler.tickEnd(ConduitNetworkTickHandler.java:47) ~[ConduitNetworkTickHandler.class:?]
        at crazypants.enderio.conduit.ConduitNetworkTickHandler.onServerTick(ConduitNetworkTickHandler.java:35) ~[ConduitNetworkTickHandler.class:?]
        at cpw.mods.fml.common.eventhandler.ASMEventHandler_78_ConduitNetworkTickHandler_onServerTick_ServerTickEvent.invoke(.dynamic) ~[?:?]
        at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:git-Cauldron-MCPC-Plus-1.7.10-1.1236.05.212]
        at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138) [EventBus.class:git-Cauldron-MCPC-Plus-1.7.10-1.1236.05.212]
        at cpw.mods.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:252) [FMLCommonHandler.class:git-Cauldron-MCPC-Plus-1.7.10-1.1236.05.212]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:851) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:658) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_11]

**Comment by tterrag1098** [comment] 2015-01-05 02:41
Duplicate of #1433

**Closed by tterrag1098** 2015-01-05 02:41 UTC
