### ISSUE TITLE
ender io skeletons in massive numbers in nether

### ISSUE THREAD

**Issue by Aegisix** [CrazyPants/EnderIO#1793] opened 2015-01-27 23:07 UTC
I was exploring a nether fortress when I found an area spawning normal textured skeletons ( waila says they were wither skeletons) in groups of 20 to 40. They drop normal skeleton drops. I can get a screen shot if necessary. Also this was in other fortresses in the nether as well. Massive hordes of these things with nothing in their hands, they attacked like zombies.. I hope this is repeatable? And fixable! 
Ps- waila says this mob is from ender io but does ender io even have a skeleton mob?

**Comment by tterrag1098** [comment] 2015-01-27 23:53
Duplicate of #1761

**Closed by tterrag1098** 2015-01-27 23:53 UTC
